package com.amazonaws.regions;

import com.amazonaws.services.s3.internal.Constants;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

class RegionDefaults {
    RegionDefaults() {
    }

    public static List<Region> getRegions() {
        ArrayList arrayList = new ArrayList();
        Region region = new Region("af-south-1", "amazonaws.com");
        arrayList.add(region);
        updateRegion(region, ServiceAbbreviations.Autoscaling, "autoscaling.af-south-1.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.Dynamodb, "dynamodb.af-south-1.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.EC2, "ec2.af-south-1.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.ElasticLoadbalancing, "elasticloadbalancing.af-south-1.amazonaws.com", false, true);
        updateRegion(region, "kms", "kms.af-south-1.amazonaws.com", false, true);
        updateRegion(region, "lambda", "lambda.af-south-1.amazonaws.com", false, true);
        updateRegion(region, "logs", "logs.af-south-1.amazonaws.com", false, true);
        updateRegion(region, "s3", "s3.af-south-1.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.SNS, "sns.af-south-1.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.SQS, "sqs.af-south-1.amazonaws.com", false, true);
        String str = ServiceAbbreviations.SQS;
        updateRegion(region, ServiceAbbreviations.STS, "sts.af-south-1.amazonaws.com", false, true);
        Region region2 = new Region("ap-northeast-1", "amazonaws.com");
        arrayList.add(region2);
        updateRegion(region2, ServiceAbbreviations.Autoscaling, "autoscaling.ap-northeast-1.amazonaws.com", false, true);
        String str2 = ServiceAbbreviations.Autoscaling;
        updateRegion(region2, "cognito-identity", "cognito-identity.ap-northeast-1.amazonaws.com", false, true);
        String str3 = "cognito-identity";
        updateRegion(region2, "cognito-idp", "cognito-idp.ap-northeast-1.amazonaws.com", false, true);
        String str4 = "cognito-idp";
        updateRegion(region2, "cognito-sync", "cognito-sync.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "data.iot", "data.iot.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, ServiceAbbreviations.Dynamodb, "dynamodb.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, ServiceAbbreviations.EC2, "ec2.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, ServiceAbbreviations.ElasticLoadbalancing, "elasticloadbalancing.ap-northeast-1.amazonaws.com", false, true);
        String str5 = ServiceAbbreviations.ElasticLoadbalancing;
        updateRegion(region2, "firehose", "firehose.ap-northeast-1.amazonaws.com", false, true);
        String str6 = "firehose";
        updateRegion(region2, "iot", "iot.ap-northeast-1.amazonaws.com", false, true);
        String str7 = "iot";
        updateRegion(region2, "kinesis", "kinesis.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "kms", "kms.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "lambda", "lambda.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "logs", "logs.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "polly", "polly.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "s3", "s3.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, ServiceAbbreviations.SimpleDB, "sdb.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, ServiceAbbreviations.SNS, "sns.ap-northeast-1.amazonaws.com", false, true);
        String str8 = str;
        updateRegion(region2, str8, "sqs.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, ServiceAbbreviations.STS, "sts.ap-northeast-1.amazonaws.com", false, true);
        Region region3 = new Region("ap-northeast-2", "amazonaws.com");
        arrayList.add(region3);
        ArrayList arrayList2 = arrayList;
        updateRegion(region3, str2, "autoscaling.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, str3, "cognito-identity.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, str4, "cognito-idp.ap-northeast-2.amazonaws.com", false, true);
        String str9 = "cognito-sync";
        updateRegion(region3, str9, "cognito-sync.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "data.iot", "data.iot.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, ServiceAbbreviations.Dynamodb, "dynamodb.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, ServiceAbbreviations.EC2, "ec2.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, str5, "elasticloadbalancing.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, str7, "iot.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "kinesis", "kinesis.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "kms", "kms.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "lambda", "lambda.ap-northeast-2.amazonaws.com", false, true);
        String str10 = "logs";
        updateRegion(region3, str10, "logs.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "polly", "polly.ap-northeast-2.amazonaws.com", false, true);
        String str11 = "s3";
        updateRegion(region3, str11, "s3.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, ServiceAbbreviations.SNS, "sns.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, str8, "sqs.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, ServiceAbbreviations.STS, "sts.ap-northeast-2.amazonaws.com", false, true);
        Region region4 = new Region("ap-south-1", "amazonaws.com");
        arrayList2.add(region4);
        String str12 = "amazonaws.com";
        updateRegion(region4, str2, "autoscaling.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, str3, "cognito-identity.ap-south-1.amazonaws.com", false, true);
        String str13 = str4;
        updateRegion(region4, str13, "cognito-idp.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, str9, "cognito-sync.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, ServiceAbbreviations.Dynamodb, "dynamodb.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, ServiceAbbreviations.EC2, "ec2.ap-south-1.amazonaws.com", false, true);
        String str14 = ServiceAbbreviations.EC2;
        String str15 = str5;
        updateRegion(region4, str15, "elasticloadbalancing.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, "kinesis", "kinesis.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, "kms", "kms.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, "lambda", "lambda.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, str10, "logs.ap-south-1.amazonaws.com", false, true);
        String str16 = str10;
        String str17 = "polly";
        updateRegion(region4, str17, "polly.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, str11, "s3.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, ServiceAbbreviations.SNS, "sns.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, str8, "sqs.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, ServiceAbbreviations.STS, "sts.ap-south-1.amazonaws.com", false, true);
        Region region5 = new Region("ap-southeast-1", str12);
        arrayList2.add(region5);
        String str18 = str2;
        String str19 = ServiceAbbreviations.STS;
        updateRegion(region5, str18, "autoscaling.ap-southeast-1.amazonaws.com", false, true);
        String str20 = str18;
        String str21 = str3;
        updateRegion(region5, str21, "cognito-identity.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, str13, "cognito-idp.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, str9, "cognito-sync.ap-southeast-1.amazonaws.com", false, true);
        String str22 = str9;
        String str23 = "data.iot";
        updateRegion(region5, str23, "data.iot.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, ServiceAbbreviations.Dynamodb, "dynamodb.ap-southeast-1.amazonaws.com", false, true);
        String str24 = ServiceAbbreviations.Dynamodb;
        String str25 = str14;
        updateRegion(region5, str25, "ec2.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, str15, "elasticloadbalancing.ap-southeast-1.amazonaws.com", false, true);
        String str26 = str15;
        String str27 = str7;
        updateRegion(region5, str27, "iot.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, "kinesis", "kinesis.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, "kms", "kms.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, "lambda", "lambda.ap-southeast-1.amazonaws.com", false, true);
        String str28 = str16;
        updateRegion(region5, str28, "logs.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, str17, "polly.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, str11, "s3.ap-southeast-1.amazonaws.com", false, true);
        String str29 = str11;
        updateRegion(region5, ServiceAbbreviations.SimpleDB, "sdb.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, ServiceAbbreviations.SNS, "sns.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, str8, "sqs.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, str19, "sts.ap-southeast-1.amazonaws.com", false, true);
        Region region6 = new Region("ap-southeast-2", str12);
        arrayList2.add(region6);
        String str30 = str20;
        updateRegion(region6, str30, "autoscaling.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, str21, "cognito-identity.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, str13, "cognito-idp.ap-southeast-2.amazonaws.com", false, true);
        String str31 = str13;
        String str32 = str22;
        updateRegion(region6, str32, "cognito-sync.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, str23, "data.iot.ap-southeast-2.amazonaws.com", false, true);
        String str33 = str23;
        String str34 = str24;
        updateRegion(region6, str34, "dynamodb.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, str25, "ec2.ap-southeast-2.amazonaws.com", false, true);
        String str35 = str32;
        String str36 = str26;
        updateRegion(region6, str36, "elasticloadbalancing.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, str27, "iot.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, "kinesis", "kinesis.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, "kms", "kms.ap-southeast-2.amazonaws.com", false, true);
        String str37 = str27;
        String str38 = "lambda";
        updateRegion(region6, str38, "lambda.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, str28, "logs.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, str17, "polly.ap-southeast-2.amazonaws.com", false, true);
        String str39 = str21;
        updateRegion(region6, str29, "s3.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, ServiceAbbreviations.SimpleDB, "sdb.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, ServiceAbbreviations.SNS, "sns.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, str8, "sqs.ap-southeast-2.amazonaws.com", false, true);
        String str40 = str19;
        updateRegion(region6, str40, "sts.ap-southeast-2.amazonaws.com", false, true);
        Region region7 = new Region("ca-central-1", str12);
        arrayList2.add(region7);
        updateRegion(region7, str30, "autoscaling.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, str34, "dynamodb.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, str25, "ec2.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, str36, "elasticloadbalancing.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, "kinesis", "kinesis.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, "kms", "kms.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, str38, "lambda.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, str28, "logs.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, str17, "polly.ca-central-1.amazonaws.com", false, true);
        String str41 = str17;
        String str42 = str29;
        updateRegion(region7, str42, "s3.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, ServiceAbbreviations.SNS, "sns.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, str8, "sqs.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, str40, "sts.ca-central-1.amazonaws.com", false, true);
        Region region8 = new Region("eu-central-1", str12);
        arrayList2.add(region8);
        updateRegion(region8, str30, "autoscaling.eu-central-1.amazonaws.com", false, true);
        String str43 = str30;
        updateRegion(region8, str39, "cognito-identity.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, str31, "cognito-idp.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, str35, "cognito-sync.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, str33, "data.iot.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, str34, "dynamodb.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, str25, "ec2.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, str36, "elasticloadbalancing.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, str6, "firehose.eu-central-1.amazonaws.com", false, true);
        String str44 = str37;
        updateRegion(region8, str44, "iot.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, "kinesis", "kinesis.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, "kms", "kms.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, str38, "lambda.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, str28, "logs.eu-central-1.amazonaws.com", false, true);
        String str45 = str41;
        updateRegion(region8, str45, "polly.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, str42, "s3.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, ServiceAbbreviations.SNS, "sns.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, str8, "sqs.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, str40, "sts.eu-central-1.amazonaws.com", false, true);
        String str46 = str12;
        Region region9 = new Region("eu-south-1", str46);
        ArrayList arrayList3 = arrayList2;
        arrayList3.add(region9);
        String str47 = str45;
        String str48 = str44;
        String str49 = "kinesis";
        String str50 = str43;
        updateRegion(region9, str50, "autoscaling.eu-south-1.amazonaws.com", false, true);
        updateRegion(region9, str34, "dynamodb.eu-south-1.amazonaws.com", false, true);
        updateRegion(region9, str25, "ec2.eu-south-1.amazonaws.com", false, true);
        updateRegion(region9, str36, "elasticloadbalancing.eu-south-1.amazonaws.com", false, true);
        updateRegion(region9, str38, "lambda.eu-south-1.amazonaws.com", false, true);
        updateRegion(region9, str28, "logs.eu-south-1.amazonaws.com", false, true);
        updateRegion(region9, str42, "s3.eu-south-1.amazonaws.com", false, true);
        updateRegion(region9, ServiceAbbreviations.SNS, "sns.eu-south-1.amazonaws.com", false, true);
        updateRegion(region9, str8, "sqs.eu-south-1.amazonaws.com", false, true);
        updateRegion(region9, str40, "sts.eu-south-1.amazonaws.com", false, true);
        Region region10 = new Region("eu-west-1", str46);
        arrayList3.add(region10);
        updateRegion(region10, str50, "autoscaling.eu-west-1.amazonaws.com", false, true);
        updateRegion(region10, str39, "cognito-identity.eu-west-1.amazonaws.com", false, true);
        updateRegion(region10, str31, "cognito-idp.eu-west-1.amazonaws.com", false, true);
        updateRegion(region10, str35, "cognito-sync.eu-west-1.amazonaws.com", false, true);
        updateRegion(region10, str33, "data.iot.eu-west-1.amazonaws.com", false, true);
        updateRegion(region10, str34, "dynamodb.eu-west-1.amazonaws.com", false, true);
        updateRegion(region10, str25, "ec2.eu-west-1.amazonaws.com", false, true);
        updateRegion(region10, str36, "elasticloadbalancing.eu-west-1.amazonaws.com", false, true);
        updateRegion(region10, "email", "email.eu-west-1.amazonaws.com", false, true);
        updateRegion(region10, str6, "firehose.eu-west-1.amazonaws.com", false, true);
        updateRegion(region10, str48, "iot.eu-west-1.amazonaws.com", false, true);
        updateRegion(region10, str49, "kinesis.eu-west-1.amazonaws.com", false, true);
        String str51 = "kms";
        updateRegion(region10, str51, "kms.eu-west-1.amazonaws.com", false, true);
        updateRegion(region10, str38, "lambda.eu-west-1.amazonaws.com", false, true);
        updateRegion(region10, str28, "logs.eu-west-1.amazonaws.com", false, true);
        String str52 = str28;
        updateRegion(region10, "machinelearning", "machinelearning.eu-west-1.amazonaws.com", false, true);
        updateRegion(region10, str47, "polly.eu-west-1.amazonaws.com", false, true);
        updateRegion(region10, "rekognition", "rekognition.eu-west-1.amazonaws.com", false, true);
        updateRegion(region10, str42, "s3.eu-west-1.amazonaws.com", false, true);
        updateRegion(region10, ServiceAbbreviations.SimpleDB, "sdb.eu-west-1.amazonaws.com", false, true);
        updateRegion(region10, ServiceAbbreviations.SNS, "sns.eu-west-1.amazonaws.com", false, true);
        updateRegion(region10, str8, "sqs.eu-west-1.amazonaws.com", false, true);
        updateRegion(region10, str40, "sts.eu-west-1.amazonaws.com", false, true);
        Region region11 = new Region("eu-west-2", str46);
        arrayList3.add(region11);
        updateRegion(region11, str43, "autoscaling.eu-west-2.amazonaws.com", false, true);
        updateRegion(region11, str39, "cognito-identity.eu-west-2.amazonaws.com", false, true);
        updateRegion(region11, str31, "cognito-idp.eu-west-2.amazonaws.com", false, true);
        updateRegion(region11, str35, "cognito-sync.eu-west-2.amazonaws.com", false, true);
        updateRegion(region11, str34, "dynamodb.eu-west-2.amazonaws.com", false, true);
        updateRegion(region11, str25, "ec2.eu-west-2.amazonaws.com", false, true);
        updateRegion(region11, str36, "elasticloadbalancing.eu-west-2.amazonaws.com", false, true);
        updateRegion(region11, str48, "iot.eu-west-2.amazonaws.com", false, true);
        String str53 = str49;
        updateRegion(region11, str53, "kinesis.eu-west-2.amazonaws.com", false, true);
        updateRegion(region11, str51, "kms.eu-west-2.amazonaws.com", false, true);
        updateRegion(region11, str38, "lambda.eu-west-2.amazonaws.com", false, true);
        String str54 = str38;
        updateRegion(region11, str52, "logs.eu-west-2.amazonaws.com", false, true);
        String str55 = str47;
        updateRegion(region11, str55, "polly.eu-west-2.amazonaws.com", false, true);
        updateRegion(region11, str42, "s3.eu-west-2.amazonaws.com", false, true);
        updateRegion(region11, ServiceAbbreviations.SNS, "sns.eu-west-2.amazonaws.com", false, true);
        updateRegion(region11, str8, "sqs.eu-west-2.amazonaws.com", false, true);
        updateRegion(region11, str40, "sts.eu-west-2.amazonaws.com", false, true);
        Region region12 = new Region("eu-west-3", str46);
        arrayList3.add(region12);
        ArrayList arrayList4 = arrayList3;
        String str56 = str43;
        updateRegion(region12, str56, "autoscaling.eu-west-3.amazonaws.com", false, true);
        updateRegion(region12, str34, "dynamodb.eu-west-3.amazonaws.com", false, true);
        updateRegion(region12, str25, "ec2.eu-west-3.amazonaws.com", false, true);
        updateRegion(region12, str36, "elasticloadbalancing.eu-west-3.amazonaws.com", false, true);
        updateRegion(region12, str53, "kinesis.eu-west-3.amazonaws.com", false, true);
        updateRegion(region12, str51, "kms.eu-west-3.amazonaws.com", false, true);
        String str57 = str51;
        updateRegion(region12, str54, "lambda.eu-west-3.amazonaws.com", false, true);
        String str58 = str52;
        updateRegion(region12, str58, "logs.eu-west-3.amazonaws.com", false, true);
        updateRegion(region12, str55, "polly.eu-west-3.amazonaws.com", false, true);
        updateRegion(region12, str42, "s3.eu-west-3.amazonaws.com", false, true);
        updateRegion(region12, ServiceAbbreviations.SNS, "sns.eu-west-3.amazonaws.com", false, true);
        updateRegion(region12, str8, "sqs.eu-west-3.amazonaws.com", false, true);
        updateRegion(region12, str40, "sts.eu-west-3.amazonaws.com", false, true);
        Region region13 = new Region("sa-east-1", str46);
        arrayList4.add(region13);
        updateRegion(region13, str56, "autoscaling.sa-east-1.amazonaws.com", false, true);
        updateRegion(region13, str34, "dynamodb.sa-east-1.amazonaws.com", false, true);
        updateRegion(region13, str25, "ec2.sa-east-1.amazonaws.com", false, true);
        updateRegion(region13, str36, "elasticloadbalancing.sa-east-1.amazonaws.com", false, true);
        updateRegion(region13, str53, "kinesis.sa-east-1.amazonaws.com", false, true);
        String str59 = str53;
        updateRegion(region13, str57, "kms.sa-east-1.amazonaws.com", false, true);
        String str60 = str54;
        updateRegion(region13, str60, "lambda.sa-east-1.amazonaws.com", false, true);
        updateRegion(region13, str58, "logs.sa-east-1.amazonaws.com", false, true);
        updateRegion(region13, str55, "polly.sa-east-1.amazonaws.com", false, true);
        updateRegion(region13, str42, "s3.sa-east-1.amazonaws.com", false, true);
        String str61 = str42;
        updateRegion(region13, ServiceAbbreviations.SimpleDB, "sdb.sa-east-1.amazonaws.com", false, true);
        updateRegion(region13, ServiceAbbreviations.SNS, "sns.sa-east-1.amazonaws.com", false, true);
        updateRegion(region13, str8, "sqs.sa-east-1.amazonaws.com", false, true);
        updateRegion(region13, str40, "sts.sa-east-1.amazonaws.com", false, true);
        Region region14 = new Region("us-east-1", str46);
        ArrayList arrayList5 = arrayList4;
        arrayList5.add(region14);
        updateRegion(region14, str56, "autoscaling.us-east-1.amazonaws.com", false, true);
        String str62 = str56;
        updateRegion(region14, str39, "cognito-identity.us-east-1.amazonaws.com", false, true);
        updateRegion(region14, str31, "cognito-idp.us-east-1.amazonaws.com", false, true);
        updateRegion(region14, str35, "cognito-sync.us-east-1.amazonaws.com", false, true);
        updateRegion(region14, str33, "data.iot.us-east-1.amazonaws.com", false, true);
        updateRegion(region14, str34, "dynamodb.us-east-1.amazonaws.com", false, true);
        updateRegion(region14, str25, "ec2.us-east-1.amazonaws.com", false, true);
        updateRegion(region14, str36, "elasticloadbalancing.us-east-1.amazonaws.com", false, true);
        updateRegion(region14, "email", "email.us-east-1.amazonaws.com", false, true);
        updateRegion(region14, str6, "firehose.us-east-1.amazonaws.com", false, true);
        updateRegion(region14, str48, "iot.us-east-1.amazonaws.com", false, true);
        updateRegion(region14, str59, "kinesis.us-east-1.amazonaws.com", false, true);
        String str63 = str57;
        updateRegion(region14, str63, "kms.us-east-1.amazonaws.com", false, true);
        updateRegion(region14, str60, "lambda.us-east-1.amazonaws.com", false, true);
        updateRegion(region14, str58, "logs.us-east-1.amazonaws.com", false, true);
        String str64 = str58;
        updateRegion(region14, "machinelearning", "machinelearning.us-east-1.amazonaws.com", false, true);
        updateRegion(region14, "mobileanalytics", "mobileanalytics.us-east-1.amazonaws.com", false, true);
        updateRegion(region14, "pinpoint", "pinpoint.us-east-1.amazonaws.com", false, true);
        updateRegion(region14, str55, "polly.us-east-1.amazonaws.com", false, true);
        updateRegion(region14, "rekognition", "rekognition.us-east-1.amazonaws.com", false, true);
        updateRegion(region14, str61, Constants.S3_HOSTNAME, false, true);
        updateRegion(region14, ServiceAbbreviations.SimpleDB, "sdb.amazonaws.com", false, true);
        updateRegion(region14, ServiceAbbreviations.SNS, "sns.us-east-1.amazonaws.com", false, true);
        updateRegion(region14, str8, "sqs.us-east-1.amazonaws.com", false, true);
        updateRegion(region14, str40, "sts.us-east-1.amazonaws.com", false, true);
        Region region15 = new Region("us-east-2", str46);
        arrayList5.add(region15);
        updateRegion(region15, str62, "autoscaling.us-east-2.amazonaws.com", false, true);
        updateRegion(region15, str39, "cognito-identity.us-east-2.amazonaws.com", false, true);
        updateRegion(region15, str31, "cognito-idp.us-east-2.amazonaws.com", false, true);
        updateRegion(region15, str35, "cognito-sync.us-east-2.amazonaws.com", false, true);
        updateRegion(region15, str34, "dynamodb.us-east-2.amazonaws.com", false, true);
        updateRegion(region15, str25, "ec2.us-east-2.amazonaws.com", false, true);
        updateRegion(region15, str36, "elasticloadbalancing.us-east-2.amazonaws.com", false, true);
        updateRegion(region15, str6, "firehose.us-east-2.amazonaws.com", false, true);
        updateRegion(region15, str48, "iot.us-east-2.amazonaws.com", false, true);
        String str65 = str59;
        updateRegion(region15, str65, "kinesis.us-east-2.amazonaws.com", false, true);
        updateRegion(region15, str63, "kms.us-east-2.amazonaws.com", false, true);
        updateRegion(region15, str60, "lambda.us-east-2.amazonaws.com", false, true);
        String str66 = str60;
        String str67 = str64;
        updateRegion(region15, str67, "logs.us-east-2.amazonaws.com", false, true);
        updateRegion(region15, str55, "polly.us-east-2.amazonaws.com", false, true);
        String str68 = str55;
        String str69 = str61;
        updateRegion(region15, str69, "s3.us-east-2.amazonaws.com", false, true);
        updateRegion(region15, ServiceAbbreviations.SNS, "sns.us-east-2.amazonaws.com", false, true);
        updateRegion(region15, str8, "sqs.us-east-2.amazonaws.com", false, true);
        updateRegion(region15, str40, "sts.us-east-2.amazonaws.com", false, true);
        Region region16 = new Region("us-west-1", str46);
        arrayList5.add(region16);
        ArrayList arrayList6 = arrayList5;
        String str70 = str62;
        updateRegion(region16, str70, "autoscaling.us-west-1.amazonaws.com", false, true);
        updateRegion(region16, str34, "dynamodb.us-west-1.amazonaws.com", false, true);
        updateRegion(region16, str25, "ec2.us-west-1.amazonaws.com", false, true);
        updateRegion(region16, str36, "elasticloadbalancing.us-west-1.amazonaws.com", false, true);
        updateRegion(region16, str65, "kinesis.us-west-1.amazonaws.com", false, true);
        updateRegion(region16, str63, "kms.us-west-1.amazonaws.com", false, true);
        String str71 = str63;
        String str72 = str66;
        updateRegion(region16, str72, "lambda.us-west-1.amazonaws.com", false, true);
        updateRegion(region16, str67, "logs.us-west-1.amazonaws.com", false, true);
        String str73 = str67;
        String str74 = str68;
        updateRegion(region16, str74, "polly.us-west-1.amazonaws.com", false, true);
        updateRegion(region16, str69, "s3.us-west-1.amazonaws.com", false, true);
        String str75 = str69;
        updateRegion(region16, ServiceAbbreviations.SimpleDB, "sdb.us-west-1.amazonaws.com", false, true);
        updateRegion(region16, ServiceAbbreviations.SNS, "sns.us-west-1.amazonaws.com", false, true);
        updateRegion(region16, str8, "sqs.us-west-1.amazonaws.com", false, true);
        updateRegion(region16, str40, "sts.us-west-1.amazonaws.com", false, true);
        Region region17 = new Region("us-west-2", str46);
        ArrayList arrayList7 = arrayList6;
        arrayList7.add(region17);
        updateRegion(region17, str70, "autoscaling.us-west-2.amazonaws.com", false, true);
        String str76 = str46;
        updateRegion(region17, str39, "cognito-identity.us-west-2.amazonaws.com", false, true);
        updateRegion(region17, str31, "cognito-idp.us-west-2.amazonaws.com", false, true);
        updateRegion(region17, str35, "cognito-sync.us-west-2.amazonaws.com", false, true);
        updateRegion(region17, str33, "data.iot.us-west-2.amazonaws.com", false, true);
        updateRegion(region17, str34, "dynamodb.us-west-2.amazonaws.com", false, true);
        updateRegion(region17, str25, "ec2.us-west-2.amazonaws.com", false, true);
        updateRegion(region17, str36, "elasticloadbalancing.us-west-2.amazonaws.com", false, true);
        updateRegion(region17, "email", "email.us-west-2.amazonaws.com", false, true);
        updateRegion(region17, str6, "firehose.us-west-2.amazonaws.com", false, true);
        String str77 = str48;
        updateRegion(region17, str77, "iot.us-west-2.amazonaws.com", false, true);
        updateRegion(region17, str65, "kinesis.us-west-2.amazonaws.com", false, true);
        String str78 = str65;
        updateRegion(region17, str71, "kms.us-west-2.amazonaws.com", false, true);
        updateRegion(region17, str72, "lambda.us-west-2.amazonaws.com", false, true);
        String str79 = str73;
        updateRegion(region17, str79, "logs.us-west-2.amazonaws.com", false, true);
        updateRegion(region17, str74, "polly.us-west-2.amazonaws.com", false, true);
        String str80 = str74;
        updateRegion(region17, "rekognition", "rekognition.us-west-2.amazonaws.com", false, true);
        updateRegion(region17, str75, "s3.us-west-2.amazonaws.com", false, true);
        updateRegion(region17, ServiceAbbreviations.SimpleDB, "sdb.us-west-2.amazonaws.com", false, true);
        updateRegion(region17, ServiceAbbreviations.SNS, "sns.us-west-2.amazonaws.com", false, true);
        updateRegion(region17, str8, "sqs.us-west-2.amazonaws.com", false, true);
        updateRegion(region17, str40, "sts.us-west-2.amazonaws.com", false, true);
        Region region18 = new Region("cn-north-1", "amazonaws.com.cn");
        arrayList7.add(region18);
        updateRegion(region18, str70, "autoscaling.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region18, str39, "cognito-identity.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region18, str34, "dynamodb.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region18, str25, "ec2.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region18, str36, "elasticloadbalancing.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region18, str77, "iot.cn-north-1.amazonaws.com.cn", false, true);
        String str81 = str78;
        updateRegion(region18, str81, "kinesis.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region18, str72, "lambda.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region18, str79, "logs.cn-north-1.amazonaws.com.cn", false, true);
        String str82 = str77;
        String str83 = str75;
        updateRegion(region18, str83, "s3.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region18, ServiceAbbreviations.SNS, "sns.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region18, str8, "sqs.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region18, str40, "sts.cn-north-1.amazonaws.com.cn", false, true);
        Region region19 = new Region("cn-northwest-1", "amazonaws.com.cn");
        arrayList7.add(region19);
        updateRegion(region19, str70, "autoscaling.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region19, str34, "dynamodb.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region19, str25, "ec2.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region19, str36, "elasticloadbalancing.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region19, str81, "kinesis.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region19, str79, "logs.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region19, str83, "s3.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region19, ServiceAbbreviations.SNS, "sns.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region19, str8, "sqs.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region19, str40, "sts.cn-northwest-1.amazonaws.com.cn", false, true);
        String str84 = str76;
        Region region20 = new Region("us-gov-west-1", str84);
        arrayList7.add(region20);
        updateRegion(region20, str70, "autoscaling.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region20, str34, "dynamodb.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region20, str25, "ec2.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region20, str36, "elasticloadbalancing.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region20, str81, "kinesis.us-gov-west-1.amazonaws.com", false, true);
        String str85 = str81;
        String str86 = str71;
        updateRegion(region20, str86, "kms.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region20, str72, "lambda.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region20, str79, "logs.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region20, "rekognition", "rekognition.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region20, str83, "s3.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region20, ServiceAbbreviations.SNS, "sns.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region20, str8, "sqs.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region20, str40, "sts.us-gov-west-1.amazonaws.com", false, true);
        Region region21 = new Region("eu-north-1", str84);
        ArrayList arrayList8 = arrayList7;
        arrayList8.add(region21);
        updateRegion(region21, str70, "autoscaling.eu-north-1.amazonaws.com", false, true);
        updateRegion(region21, str34, "dynamodb.eu-north-1.amazonaws.com", false, true);
        updateRegion(region21, str25, "ec2.eu-north-1.amazonaws.com", false, true);
        updateRegion(region21, str36, "elasticloadbalancing.eu-north-1.amazonaws.com", false, true);
        String str87 = str36;
        updateRegion(region21, str6, "firehose.eu-north-1.amazonaws.com", false, true);
        updateRegion(region21, str82, "iot.eu-north-1.amazonaws.com", false, true);
        String str88 = str85;
        updateRegion(region21, str88, "kinesis.eu-north-1.amazonaws.com", false, true);
        updateRegion(region21, str86, "kms.eu-north-1.amazonaws.com", false, true);
        updateRegion(region21, str72, "lambda.eu-north-1.amazonaws.com", false, true);
        String str89 = str72;
        String str90 = str79;
        updateRegion(region21, str90, "logs.eu-north-1.amazonaws.com", false, true);
        updateRegion(region21, str83, "s3.eu-north-1.amazonaws.com", false, true);
        updateRegion(region21, ServiceAbbreviations.SNS, "sns.eu-north-1.amazonaws.com", false, true);
        updateRegion(region21, str8, "sqs.eu-north-1.amazonaws.com", false, true);
        updateRegion(region21, str40, "sts.eu-north-1.amazonaws.com", false, true);
        Region region22 = new Region("ap-east-1", str84);
        arrayList8.add(region22);
        updateRegion(region22, str70, "autoscaling.ap-east-1.amazonaws.com", false, true);
        updateRegion(region22, str34, "dynamodb.ap-east-1.amazonaws.com", false, true);
        updateRegion(region22, str25, "ec2.ap-east-1.amazonaws.com", false, true);
        String str91 = str25;
        updateRegion(region22, str87, "elasticloadbalancing.ap-east-1.amazonaws.com", false, true);
        String str92 = str6;
        updateRegion(region22, str92, "firehose.ap-east-1.amazonaws.com", false, true);
        updateRegion(region22, str88, "kinesis.ap-east-1.amazonaws.com", false, true);
        updateRegion(region22, str86, "kms.ap-east-1.amazonaws.com", false, true);
        String str93 = str86;
        String str94 = str89;
        updateRegion(region22, str94, "lambda.ap-east-1.amazonaws.com", false, true);
        updateRegion(region22, str90, "logs.ap-east-1.amazonaws.com", false, true);
        String str95 = str90;
        String str96 = str80;
        updateRegion(region22, str96, "polly.ap-east-1.amazonaws.com", false, true);
        updateRegion(region22, str83, "s3.ap-east-1.amazonaws.com", false, true);
        updateRegion(region22, ServiceAbbreviations.SNS, "sns.ap-east-1.amazonaws.com", false, true);
        updateRegion(region22, str8, "sqs.ap-east-1.amazonaws.com", false, true);
        updateRegion(region22, str40, "sts.ap-east-1.amazonaws.com", false, true);
        Region region23 = new Region("me-south-1", str84);
        arrayList8.add(region23);
        updateRegion(region23, str70, "autoscaling.me-south-1.amazonaws.com", false, true);
        String str97 = str70;
        updateRegion(region23, str39, "cognito-identity.me-south-1.amazonaws.com", false, true);
        updateRegion(region23, str31, "cognito-idp.me-south-1.amazonaws.com", false, true);
        updateRegion(region23, str35, "cognito-sync.me-south-1.amazonaws.com", false, true);
        String str98 = str33;
        updateRegion(region23, str98, "data.iot.me-south-1.amazonaws.com", false, true);
        updateRegion(region23, str34, "dynamodb.me-south-1.amazonaws.com", false, true);
        String str99 = str34;
        updateRegion(region23, str91, "ec2.me-south-1.amazonaws.com", false, true);
        String str100 = str87;
        updateRegion(region23, str100, "elasticloadbalancing.me-south-1.amazonaws.com", false, true);
        updateRegion(region23, str92, "firehose.me-south-1.amazonaws.com", false, true);
        String str101 = str92;
        String str102 = str82;
        updateRegion(region23, str102, "iot.me-south-1.amazonaws.com", false, true);
        updateRegion(region23, str88, "kinesis.me-south-1.amazonaws.com", false, true);
        String str103 = str88;
        String str104 = str93;
        updateRegion(region23, str104, "kms.me-south-1.amazonaws.com", false, true);
        updateRegion(region23, str94, "lambda.me-south-1.amazonaws.com", false, true);
        String str105 = str94;
        String str106 = str95;
        updateRegion(region23, str106, "logs.me-south-1.amazonaws.com", false, true);
        updateRegion(region23, str96, "polly.me-south-1.amazonaws.com", false, true);
        updateRegion(region23, str83, "s3.me-south-1.amazonaws.com", false, true);
        updateRegion(region23, ServiceAbbreviations.SimpleDB, "sdb.me-south-1.amazonaws.com", false, true);
        updateRegion(region23, ServiceAbbreviations.SNS, "sns.me-south-1.amazonaws.com", false, true);
        updateRegion(region23, str8, "sqs.me-south-1.amazonaws.com", false, true);
        updateRegion(region23, str40, "sts.me-south-1.amazonaws.com", false, true);
        Region region24 = new Region("ap-southeast-3", str84);
        arrayList8.add(region24);
        updateRegion(region24, str97, "autoscaling.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region24, str39, "cognito-identity.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region24, str31, "cognito-idp.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region24, str35, "cognito-sync.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region24, str98, "data.iot.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region24, str99, "dynamodb.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region24, str91, "ec2.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region24, str100, "elasticloadbalancing.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region24, str101, "firehose.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region24, str102, "iot.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region24, str103, "kinesis.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region24, str104, "kms.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region24, str105, "lambda.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region24, str106, "logs.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region24, str96, "polly.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region24, str83, "s3.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region24, ServiceAbbreviations.SimpleDB, "sdb.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region24, ServiceAbbreviations.SNS, "sns.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region24, str8, "sqs.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region24, str40, "sts.ap-southeast-3.amazonaws.com", false, true);
        return arrayList8;
    }

    private static void updateRegion(Region region, String str, String str2, boolean z, boolean z2) {
        Map<String, String> serviceEndpoints = region.getServiceEndpoints();
        Map<String, Boolean> httpSupport = region.getHttpSupport();
        Map<String, Boolean> httpsSupport = region.getHttpsSupport();
        serviceEndpoints.put(str, str2);
        httpSupport.put(str, Boolean.valueOf(z));
        httpsSupport.put(str, Boolean.valueOf(z2));
    }
}
